name: example
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.7+7

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  runpoint_app_commons:
    path: ..
  cupertino_icons: ^1.0.8
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  el_dart:
    git:
      url: https://github.com/luoyi58624/el.git
      path: packages/el_dart
  el_flutter:
    git:
      url: https://github.com/luoyi58624/el.git
      path: packages/el_flutter
  el_state:
    git:
      url: https://github.com/luoyi58624/el.git
      path: packages/el_state
  el_storage:
    git:
      url: https://github.com/luoyi58624/el.git
      path: packages/el_storage
  el_http:
    git:
      url: https://github.com/luoyi58624/el.git
      path: packages/el_http

flutter:
  uses-material-design: true
