name: runpoint_app_commons
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  el_dart: ^0.0.10
  el_flutter: ^0.0.6
  el_ui:
    git:
      url: https://github.com/luoyi58624/el
      path: packages/el_ui
  flutter_exit_plugin: ^0.0.1
  package_info_plus: ^9.0.0
  shorebird_code_push: ^2.0.5
  path_provider: ^2.1.5
  path: ^1.9.1
  android_package_installer: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
